set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/gray_code_gen.v
#set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/ram_gen.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/fifo_gen.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/sync_ff.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/edge_detect.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/clock_gen.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/interrupt_gen.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cm3/cortexm3ds_logic.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cm3/CORTEXM3INTEGRATIONDS.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_i.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_lite.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM0.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM1.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM5.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS2.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM5.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM6.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM7.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM0.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM6.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM7.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS1.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_default_slave.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM1.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS0.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_p.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_h.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb/verilog/cmsdk_ahb_to_apb.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_syn.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_apb_slave_mux/verilog/cmsdk_apb_slave_mux.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_sram/verilog/cmsdk_ahb_to_sram.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_fpga_sram/verilog/cmsdk_fpga_sram.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/gen_apb/debug0_apb_cfg.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/library/gen_apb/debug1_apb_cfg.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/fp_domain.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/apb0_top.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/apb1_top.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/sram/sram_top.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_rx.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_tx.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_core.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_apb_cfg.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_data_buffer.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_regs_wrap.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_top.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_apb_cfg.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/pad.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_regs_wrap.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpioa_mux.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_top.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_normal.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_pad.v
set_global_assignment -name VERILOG_FILE /home/master/project/cm3_ahbmtx_mcu/user/verilog/mcu_top.v
