SIM_TARGET := fpga_7020_sram_wr_sim
SIM_DEFINE := +define+FSDB_DUMP +define+SRAM_WR_SIM +define+FPGA_SRAM +define+ZYNQ_7020
SIM_PATH := ${PRJ_SIM_DIR}/${SIM_TARGET}
DUT_LIST := dut.list
SIM_LIST := zynq_sim.list
SIM_INC_LIST := sim_inc.list
SIM_SCRIPTS_PATH := ${PRJ_SIM_DIR}/script
CMDFILE := ${SIM_SCRIPTS_PATH}/vcs_sim_cmdfile.f
WAVEFORM := TOP.fsdb
WAVELIST := ${SIM_SCRIPTS_PATH}/sram.rc
SHELL := /bin/bash

all: prepare compile sim waveform

prepare:
	-mkdir ${SIM_PATH}
	cp ${DUT_LIST} ${SIM_PATH}
	cp ${SIM_LIST} ${SIM_PATH}
	cp ${SIM_INC_LIST} ${SIM_PATH}
	cp ${CMDFILE} ${SIM_PATH}
	source vcs_sim_prepare.sh ${PRJ_DIR} ${SIM_PATH}

compile:
	cd ${SIM_PATH} && vcs ${SIM_DEFINE} -full64 -f ${CMDFILE} -P ${VERDI_DT} ${VERDI_DA} -f ${SIM_INC_LIST} -f ${SIM_LIST} -f ${DUT_LIST} 

sim:
	cd ${SIM_PATH} && ./simv -l sim.log

waveform:
	cd ${SIM_PATH} && verdi ${SIM_DEFINE} -f ${CMDFILE} -f ${SIM_INC_LIST} -f ${SIM_LIST} -f ${DUT_LIST} -ssf ${WAVEFORM} -sswr ${WAVELIST} &
 
#clean:

