FPGA_TARGET := fpga_7020_mcu_full_vivado
TOP_NAME := mcu_top
FPGA_DEFINE := "\`define+FPGA \`define+FPGA_SRAM \`define+ZYNQ_7020 \`define+UART0"
DUT_LIST := dut.list
FPGA_DUT_LIST := fpga_7020_dut.list
FPGA_IP_LIST := fpga_7020_ip.list
FPGA_CFG_LIST := fpga_7020_mcu_full_cfg.tcl
PIN_LIST := fpga_7020_mcu_full_pin_assignments.xdc
TIMING_CONSTRAIN_LIST := fpga_7020_mcu_full_timing_constrain.xdc
FPGA_PATH := ${PRJ_FPGA_DIR}/${FPGA_TARGET}

SDK_TARGET := bootloader
SDK_DEFINE := -D__NO_SYSTEM_INIT -DUART_DRIVER -DCOMMON_DRIVER

SDK_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}
BUILD_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/build
OUTPUT_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/output
FW_PATH := ${PRJ_FW_DIR}/${SDK_TARGET}
FW_INC_PATH := -I ${PRJ_FW_DIR}/${SDK_TARGET}/boot/inc

CPU_INC_PATH := -I ${PRJ_LIB_DIR}/cmsis/CMSIS/Include -I ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Include
DRV_INC_PATH := -I ${PRJ_DRV_DIR} -I ${PRJ_DRV_DIR}/common/inc -I ${PRJ_DRV_DIR}/uart/inc
INC_PATH := ${FW_INC_PATH} ${DRV_INC_PATH} ${CPU_INC_PATH} 

LDSCRIPT := ${FW_PATH}/bootloader_itcm.ld
STARTUP_S := ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Source/GCC/startup_CM3DS.s

CFLAG := -std=c99 -DPRJ=${SDK_TARGET} -D__GNUC__=9 -Og -Wall -Wextra -fdata-sections -ffunction-sections
ARCH_FLAG := -mthumb -mthumb-interwork -mcpu=cortex-m3
LDFLAG := -Wl,-gc-sections -Wl,-Map=${SDK_TARGET}.map,--cref -specs=nano.specs -specs=nosys.specs
FLAG := ${CFLAG} ${ARCH_FLAG}

SHELL := /bin/bash

all: prepare build_driver build_bootloader vivado_compile

prepare:
	-mkdir ${SDK_PATH}
	-mkdir ${BUILD_PATH}
	-mkdir ${OUTPUT_PATH}
	-mkdir ${FPGA_PATH}
	cp ${DUT_LIST} ${FPGA_PATH}
	cp ${FPGA_DUT_LIST} ${FPGA_PATH}
	cp ${FPGA_IP_LIST} ${FPGA_PATH}
	cp ${PRJ_FPGA_SCR_DIR}/${FPGA_CFG_LIST} ${FPGA_PATH}
	cp ${PRJ_FPGA_SCR_DIR}/${PIN_LIST} ${FPGA_PATH}
	cp ${PRJ_FPGA_SCR_DIR}/${TIMING_CONSTRAIN_LIST} ${FPGA_PATH}
	cp vivado_top.tcl ${FPGA_PATH}/${TOP_NAME}.tcl
	source vivado_prepare.sh ${PRJ_DIR} ${FPGA_PATH} ${TOP_NAME} ${FPGA_DEFINE} ${FPGA_CFG_LIST} ${PIN_LIST} ${TIMING_CONSTRAIN_LIST}

build_driver:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/common/src/drv_common.c -o ${BUILD_PATH}/drv_common.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart.c -o ${BUILD_PATH}/drv_uart.o

build_bootloader:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/main.c -o ${BUILD_PATH}/main.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/interrupt.c -o ${BUILD_PATH}/interrupt.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${STARTUP_S} -o ${BUILD_PATH}/startup_CM3DS.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc -T ${LDSCRIPT} ${ARCH_FLAG} *.o -o ${SDK_TARGET}.elf ${LDFLAG}
	mv ${BUILD_PATH}/${SDK_TARGET}.elf ${OUTPUT_PATH}
	mv ${BUILD_PATH}/${SDK_TARGET}.map ${OUTPUT_PATH}
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O binary -S ${SDK_TARGET}.elf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O ihex -S ${SDK_TARGET}.elf ${SDK_TARGET}.hex
	cp ${OUTPUT_PATH}/${SDK_TARGET}.bin ${FPGA_PATH}
	cd ${FPGA_PATH} && xxd -g 4 -c 4 -p ${SDK_TARGET}.bin > ${SDK_TARGET}.txt
	cd ${FPGA_PATH} && rm -rf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objdump -D ${SDK_TARGET}.elf > ${SDK_TARGET}.asm
	source lsb2msb.sh ${FPGA_PATH} ${SDK_TARGET}.txt 
	cd ${FPGA_PATH} && cp ${SDK_TARGET}.txt	${SDK_TARGET}.mem

vivado_compile:
	cd ${FPGA_PATH} && vivado -mode tcl -source ${TOP_NAME}.tcl -log run.log
#	cd ${FPGA_PATH} && cp -r ${TOP_NAME}.gen/sources_1 ${PRJ_MOD_DIR}/xilinx_ip/

#clean:

