#===============================================
#
#		File: makefile
#		Author: afterGlow,4ever
#		Group: Fall For Laboratory
#		Date: 07292023
#		Version: v1.0
#
# 	This is script top for any operation in this project.
# 	Including:
# 	1. RTL simulation
# 	2. RTL auto generation
#
#===============================================

#===============================================
# RTL simulation
#===============================================

cpu_swd_sim:
	make -f makefile.cpu_swd_sim

cpu_bus_sim:
	make -f makefile.cpu_bus_sim

#===============================================
# RTL auto generation
#===============================================

ahbmtx_gen:
	make -f makefile.ahbmtx_gen

