SDK_TARGET := fw_test
SDK_DEFINE := -D__NO_SYSTEM_INIT -DUART_DRIVER -DUART_EX_DRIVER -DADVTIM_DRIVER -DCOMMON_DRIVER -DADVTIM_TEST 

SDK_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}
BUILD_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/build
OUTPUT_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/output
FW_PATH := ${PRJ_FW_DIR}/${SDK_TARGET}
FW_INC_PATH := -I ${PRJ_FW_DIR}/${SDK_TARGET} -I ${PRJ_FW_DIR}/${SDK_TARGET}/uart_bsp -I ${PRJ_FW_DIR}/${SDK_TARGET}/advtim_bsp

CPU_INC_PATH := -I ${PRJ_LIB_DIR}/cmsis/CMSIS/Include -I ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Include
DRV_INC_PATH := -I ${PRJ_DRV_DIR} -I ${PRJ_DRV_DIR}/common/inc -I ${PRJ_DRV_DIR}/uart/inc -I ${PRJ_DRV_DIR}/advtim/inc
INC_PATH := ${FW_INC_PATH} ${DRV_INC_PATH} ${CPU_INC_PATH} 

LDSCRIPT := ${FW_PATH}/itcm.ld
STARTUP_S := ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Source/GCC/startup_CM3DS.s

CFLAG := -std=c99 -DPRJ=${SDK_TARGET} -D__GNUC__=9 -Og -Wall -Wextra -fdata-sections -ffunction-sections
ARCH_FLAG := -mthumb -mthumb-interwork -mcpu=cortex-m3
LDFLAG := -Wl,-gc-sections -Wl,-Map=${SDK_TARGET}.map,--cref -specs=nano.specs -specs=nosys.specs
FLAG := ${CFLAG} ${ARCH_FLAG}

SHELL := /bin/bash

all: prepare build_driver build_fw

prepare:
	-mkdir ${SDK_PATH}
	-mkdir ${BUILD_PATH}
	-mkdir ${OUTPUT_PATH}

build_driver:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/common/src/drv_common.c -o ${BUILD_PATH}/drv_common.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart.c -o ${BUILD_PATH}/drv_uart.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart_ex.c -o ${BUILD_PATH}/drv_uart_ex.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/advtim/src/drv_advtim_gen.c -o ${BUILD_PATH}/drv_advtim_gen.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/advtim/src/drv_advtim_cap.c -o ${BUILD_PATH}/drv_advtim_cap.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/advtim/src/drv_advtim_enc.c -o ${BUILD_PATH}/drv_advtim_enc.o

build_fw:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/uart_bsp/uart_bsp.c -o ${BUILD_PATH}/uart_bsp.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/uart_bsp/uart_test.c -o ${BUILD_PATH}/uart_test.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/advtim_bsp/advtim_bsp.c -o ${BUILD_PATH}/advtim_bsp.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/advtim_bsp/advtim_test.c -o ${BUILD_PATH}/advtim_test.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/main.c -o ${BUILD_PATH}/main.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/interrupt.c -o ${BUILD_PATH}/interrupt.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${STARTUP_S} -o ${BUILD_PATH}/startup_CM3DS.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc -T ${LDSCRIPT} ${ARCH_FLAG} *.o -o ${SDK_TARGET}.elf ${LDFLAG}
	mv ${BUILD_PATH}/${SDK_TARGET}.elf ${OUTPUT_PATH}
	mv ${BUILD_PATH}/${SDK_TARGET}.map ${OUTPUT_PATH}
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O binary -S ${SDK_TARGET}.elf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O ihex -S ${SDK_TARGET}.elf ${SDK_TARGET}.hex
	cd ${OUTPUT_PATH} && arm-none-eabi-objdump -D ${SDK_TARGET}.elf > ${SDK_TARGET}.asm

#clean:

