SIM_TARGET := fpga_ep4_cpu_itcm_boot_sim
SIM_DEFINE := +define+FSDB_DUMP +define+CPU_ITCM_BOOT +define+UART0 +define+SRAM_128K +define+FPGA +define+FPGA_SRAM +define+ALTERA_EP4
SIM_PATH := ${PRJ_SIM_DIR}/${SIM_TARGET}
DUT_LIST := dut.list
SIM_LIST := sim.list
SIM_INC_LIST := sim_inc.list
SIM_SCRIPTS_PATH := ${PRJ_SIM_DIR}/script
CMDFILE := ${SIM_SCRIPTS_PATH}/vcs_sim_cmdfile.f
WAVEFORM := TOP.fsdb
WAVELIST := ${SIM_SCRIPTS_PATH}/boot.rc

SDK_TARGET := bootloader
SDK_DEFINE := -D__NO_SYSTEM_INIT -DUART_DRIVER -DCOMMON_DRIVER

SDK_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}
BUILD_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/build
OUTPUT_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/output
FW_PATH := ${PRJ_FW_DIR}/${SDK_TARGET}
FW_INC_PATH := -I ${PRJ_FW_DIR}/${SDK_TARGET}/boot/inc

CPU_INC_PATH := -I ${PRJ_LIB_DIR}/cmsis/CMSIS/Include -I ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Include
DRV_INC_PATH := -I ${PRJ_DRV_DIR} -I ${PRJ_DRV_DIR}/common/inc -I ${PRJ_DRV_DIR}/uart/inc
INC_PATH := ${FW_INC_PATH} ${DRV_INC_PATH} ${CPU_INC_PATH} 

LDSCRIPT := ${FW_PATH}/bootloader_itcm.ld
STARTUP_S := ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Source/GCC/startup_CM3DS.s

CFLAG := -std=c99 -DPRJ=${SDK_TARGET} -D__GNUC__=9 -Og -Wall -Wextra -fdata-sections -ffunction-sections
ARCH_FLAG := -mthumb -mthumb-interwork -mcpu=cortex-m3
LDFLAG := -Wl,-gc-sections -Wl,-Map=${SDK_TARGET}.map,--cref -specs=nano.specs -specs=nosys.specs
FLAG := ${CFLAG} ${ARCH_FLAG}

SHELL := /bin/bash

#all: prepare build_driver build_bootloader compile_rtl sim waveform
all:  waveform

prepare:
	-mkdir ${SDK_PATH}
	-mkdir ${BUILD_PATH}
	-mkdir ${OUTPUT_PATH}
	-mkdir ${SIM_PATH}
	cp ${DUT_LIST} ${SIM_PATH}
	cp ${SIM_LIST} ${SIM_PATH}
	cp ${SIM_INC_LIST} ${SIM_PATH}
	cp ${CMDFILE} ${SIM_PATH}
	source vcs_sim_prepare.sh ${PRJ_DIR} ${SIM_PATH}

build_driver:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/common/src/drv_common.c -o ${BUILD_PATH}/drv_common.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${PRJ_DRV_DIR}/uart/src/drv_uart.c -o ${BUILD_PATH}/drv_uart.o

build_bootloader:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/main.c -o ${BUILD_PATH}/main.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${FW_PATH}/boot/src/interrupt.c -o ${BUILD_PATH}/interrupt.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${INC_PATH} -c ${STARTUP_S} -o ${BUILD_PATH}/startup_CM3DS.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc -T ${LDSCRIPT} ${ARCH_FLAG} *.o -o ${SDK_TARGET}.elf ${LDFLAG}
	mv ${BUILD_PATH}/${SDK_TARGET}.elf ${OUTPUT_PATH}
	mv ${BUILD_PATH}/${SDK_TARGET}.map ${OUTPUT_PATH}
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O binary -S ${SDK_TARGET}.elf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O ihex -S ${SDK_TARGET}.elf ${SDK_TARGET}.hex
	cp ${OUTPUT_PATH}/${SDK_TARGET}.bin ${SIM_PATH}
	cd ${SIM_PATH} && xxd -g 4 -c 4 -p ${SDK_TARGET}.bin > ${SDK_TARGET}.txt
	cd ${OUTPUT_PATH} && arm-none-eabi-objdump -D ${SDK_TARGET}.elf > ${SDK_TARGET}.asm
	source lsb2msb.sh ${SIM_PATH} ${SDK_TARGET}.txt 
	source txt2mif.sh ${SIM_PATH} ${SDK_TARGET}.txt 2048 32 ${SDK_TARGET}.mif

compile_rtl:
	cd ${SIM_PATH} && vcs ${SIM_DEFINE} -full64 -f ${CMDFILE} -P ${VERDI_DT} ${VERDI_DA} -f ${SIM_INC_LIST} -f ${SIM_LIST} -f ${DUT_LIST} 

sim:
	cd ${SIM_PATH} && ./simv -l sim.log

waveform:
	cd ${SIM_PATH} && verdi ${SIM_DEFINE} -f ${CMDFILE} -f ${SIM_INC_LIST} -f ${SIM_LIST} -f ${DUT_LIST} -ssf ${WAVEFORM} -sswr ${WAVELIST} &
 
#clean:

