FPGA_TARGET := fpga_ep4_mcu_full_quartus
TOP_NAME := mcu_top
FPGA_DEFINE := "\`define+FSDB_DUMP \`define+FPGA \`define+FPGA_SRAM \`define+ALTERA_EP4"
FPGA_PATH := ${PRJ_FPGA_DIR}/${FPGA_TARGET}
DUT_LIST := dut.list
FPGA_DUT_LIST := fpga_ep4_dut.list
FPGA_CFG_LIST := fpga_ep4_mcu_full_cfg.tcl
PIN_LIST := fpga_ep4_mcu_full_pin_assignments.tcl
TIMING_CONSTRAIN_LIST := fpga_ep4_mcu_full_timing_constrain.sdc
FPGA_SCRIPTS_PATH := ${PRJ_FPGA_DIR}/script

SDK_TARGET := bootloader
SDK_DEFINE := -D__NO_SYSTEM_INIT

SDK_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}
BUILD_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/build
OUTPUT_PATH := ${PRJ_SDK_DIR}/${SDK_TARGET}/output
FW_PATH := ${PRJ_FW_DIR}/${SDK_TARGET}
FW_INC := -I ${PRJ_FW_DIR}/${SDK_TARGET}/boot/inc
CPU_INC := -I ${PRJ_LIB_DIR}/cmsis/CMSIS/Include -I ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Include
BASE_INC := -I ${PRJ_DRV_DIR}
SDK_INC := ${FW_INC} ${BASE_INC} ${CPU_INC} 

LDSCRIPT := ${FW_PATH}/bootloader_itcm.ld
STARTUP_S := ${PRJ_LIB_DIR}/cmsis/Device/ARM/CM3DS/Source/GCC/startup_CM3DS.s

CFLAG := -std=c99 -DPRJ=${SDK_TARGET} -D__GNUC__=9 -Og -Wall -Wextra -fdata-sections -ffunction-sections
ARCH_FLAG := -mthumb -mthumb-interwork -mcpu=cortex-m3
LDFLAG := -Wl,-gc-sections -Wl,-Map=${SDK_TARGET}.map,--cref -specs=nano.specs -specs=nosys.specs
FLAG := ${CFLAG} ${ARCH_FLAG}

SHELL := /bin/bash

all: prepare build_bootloader quartus_setup map fit asm sta
#all: prepare build_bootloader 

prepare:
	-mkdir ${SDK_PATH}
	-mkdir ${BUILD_PATH}
	-mkdir ${OUTPUT_PATH}
	-mkdir ${FPGA_PATH}
	cp ${DUT_LIST} ${FPGA_PATH}
	cp ${FPGA_DUT_LIST} ${FPGA_PATH}
	cp ${FPGA_SCRIPTS_PATH}/${FPGA_CFG_LIST} ${FPGA_PATH}
	cp ${FPGA_SCRIPTS_PATH}/${PIN_LIST} ${FPGA_PATH}
	cp ${FPGA_SCRIPTS_PATH}/${TIMING_CONSTRAIN_LIST} ${FPGA_PATH}
	cp quartus_top.tcl ${FPGA_PATH}/${TOP_NAME}.tcl
	source quartus_prepare.sh ${PRJ_DIR} ${FPGA_PATH} ${TOP_NAME} ${FPGA_DEFINE} ${FPGA_CFG_LIST} ${PIN_LIST} ${TIMING_CONSTRAIN_LIST}

build_bootloader:
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${SDK_INC} -c ${FW_PATH}/boot/src/main.c -o ${BUILD_PATH}/main.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${SDK_INC} -c ${FW_PATH}/boot/src/interrupt.c -o ${BUILD_PATH}/interrupt.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc ${SDK_DEFINE} ${FLAG} ${SDK_INC} -c ${STARTUP_S} -o ${BUILD_PATH}/startup_CM3DS.o
	cd ${BUILD_PATH} && arm-none-eabi-gcc -T ${LDSCRIPT} ${ARCH_FLAG} *.o -o ${SDK_TARGET}.elf ${LDFLAG}
	mv ${BUILD_PATH}/${SDK_TARGET}.elf ${OUTPUT_PATH}
	mv ${BUILD_PATH}/${SDK_TARGET}.map ${OUTPUT_PATH}
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O binary -S ${SDK_TARGET}.elf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objcopy -O ihex -S ${SDK_TARGET}.elf ${SDK_TARGET}.hex
	cp ${OUTPUT_PATH}/${SDK_TARGET}.bin ${FPGA_PATH}
	cd ${FPGA_PATH} && xxd -g 4 -c 4 -p ${SDK_TARGET}.bin > ${SDK_TARGET}.txt
	cd ${FPGA_PATH} && rm -rf ${SDK_TARGET}.bin
	cd ${OUTPUT_PATH} && arm-none-eabi-objdump -D ${SDK_TARGET}.elf > ${SDK_TARGET}.asm
	source lsb2msb.sh ${FPGA_PATH} ${SDK_TARGET}.txt 
	source txt2mif.sh ${FPGA_PATH} ${SDK_TARGET}.txt 2048 32 ${SDK_TARGET}.mif

quartus_setup:
	cd ${FPGA_PATH} && quartus_sh -t ${TOP_NAME}.tcl

map:
	cd ${FPGA_PATH} && quartus_map ${TOP_NAME} | tee -a run.log

fit:
	cd ${FPGA_PATH} && quartus_fit ${TOP_NAME} | tee -a run.log

asm:
	cd ${FPGA_PATH} && quartus_asm ${TOP_NAME} | tee -a run.log

sta:
	cd ${FPGA_PATH} && quartus_sta ${TOP_NAME} | tee -a run.log

#clean:

