read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/gray_code_gen.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/fifo_gen.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/sync_ff.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/edge_detect.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/delay_detect.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/clock_gen.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/interrupt_gen.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/pulse_sync.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/rst_sync.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/crc.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/sp_sram/sp_sram_1k_256x32_wrapper.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/sp_sram/sp_sram_2k_2048x8_wrapper.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/rtl_logic/sp_sram/sp_sram_2k_512x32_wrapper.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cm3/cortexm3ds_logic.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cm3/CORTEXM3INTEGRATIONDS.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_i.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_lite.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM0.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM1.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS2.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM6.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM7.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM8.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_oM0.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM6.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM7.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM8.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS1.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS4.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_default_slave.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_arbiterM1.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_busmatrix/verilog/built/ahb_bus_matrix/ahb_bus_matrix_decoderS0.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_p.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_h.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb/verilog/cmsdk_ahb_to_apb.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_apb_async/verilog/cmsdk_ahb_to_apb_async_syn.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_apb_slave_mux/verilog/cmsdk_apb_slave_mux.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_ahb_to_sram/verilog/cmsdk_ahb_to_sram.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/cmsdk/cmsdk_fpga_sram/verilog/cmsdk_fpga_sram.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/library/gen_apb/debug0_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/fp_domain.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/apb0_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/apb1_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/domain/apb2_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/sram/sram_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_rx.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_tx.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_pe_core/uart_pe_core.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_data_buffer.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_regs_wrap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/uart/uart_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/pad.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_regs_wrap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpioa_mux.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_normal.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/gpio/gpio_pad.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/bastim/bastim_regs_wrap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/bastim/bastim_ch_core/bastim_ch.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/bastim/bastim_ch_core/bastim_ch_core.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/bastim/bastim_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/bastim/bastim_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/eth_sma_pe_master.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/eth_pe_core.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_regs_wrap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_sma_data_buffer.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/eth_mac_pe_tx.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/eth_mac_pe_tx_protocol_handle.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/hw_header_checksum_without_pseudoheader.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_pe_core/hw_header_checksum_with_pseudoheader.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_mac_data_buffer/eth_mac_data_tx_buffer.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_mac_data_buffer/eth_ahb_master.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_mac_data_buffer/eth_ahb_master_arbiter.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_mac_data_buffer/eth_descriptor_handler.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/eth/eth_mac_data_buffer/eth_mac_data_buffer.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_regs_wrap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/advtim_cnt_gen.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/advtim_cnt_cap.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/advtim_cnt_enc.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/advtim_pe_core.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/channel_output_compare.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/channel_input_capture.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/channel_encoder_input.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/channel_ctrl.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/deadzone.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_pe_core/fault_detection.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_top.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/advtim/advtim_apb_cfg.v
read_verilog /home/master/project/cm3_ahbmtx_mcu/user/verilog/mcu_top.v

